CREATE TABLE daily_summary (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    date DATE NOT NULL UNIQUE,
    summaries JSONB,
    categories JSONB,
    "references" JSONB
);

CREATE TABLE article (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    url TEXT NOT NULL,
    published_at TIMESTAMPTZ,
    title TEXT,
    description TEXT,
    source TEXT,
    daily_summary_id INT REFERENCES daily_summary(id) ON DELETE SET NULL
);
